---
version: "3.9"
services:
  backend:
    image: python:3.8.5
    working_dir: /app
    command: ["./run.sh"]
    volumes:
      - ./backend:/app:delegated
    environment:
      - DB_SCHEMA=afs
      - DB_USER=akvo
      - DB_PASSWORD=password
      - DB_HOST=db
      - DEBUG=True
      - DJANGO_SECRET=local-secret
    depends_on:
      - db
  frontend:
    image: akvo/akvo-node-18-alpine:20230831.105309.b9593b7
    command: ["./start.sh"]
    volumes:
      - ./frontend:/app:delegated
    working_dir: /app
    depends_on:
      - backend
  db:
    image: postgres:12-alpine
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
volumes:
  pg-data:
