# Generated by Django 4.2.1 on 2023-08-31 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(default=None, null=True)),
                ('version', models.IntegerField(default=1)),
                ('languages', models.JSONField(default=None, null=True)),
                ('default_language', models.CharField(default=None, max_length=255, null=True)),
                ('translations', models.JSONField(default=None, null=True)),
            ],
            options={
                'db_table': 'forms',
            },
        ),
        migrations.CreateModel(
            name='QuestionGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(default=None, null=True)),
                ('order', models.BigIntegerField(default=None, null=True)),
                ('repeatable', models.BooleanField(default=False)),
                ('translations', models.JSONField(default=None, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_groups', to='core_forms.forms')),
            ],
            options={
                'db_table': 'question_groups',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('order', models.BigIntegerField(default=None, null=True)),
                ('type', models.IntegerField(choices=[(2, 'input'), (3, 'text'), (4, 'number'), (1, 'geo'), (5, 'option'), (6, 'multiple_pption'), (7, 'cascade'), (8, 'photo'), (9, 'date'), (10, 'autofield')])),
                ('tooltip', models.JSONField(default=None, null=True)),
                ('required', models.BooleanField(default=True)),
                ('meta', models.BooleanField(default=False)),
                ('rule', models.JSONField(default=None, null=True)),
                ('dependency', models.JSONField(default=None, null=True)),
                ('api', models.JSONField(default=None, null=True)),
                ('extra', models.JSONField(default=None, null=True)),
                ('autofield', models.JSONField(default=None, null=True)),
                ('translations', models.JSONField(default=None, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core_forms.forms')),
                ('question_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_group_questions', to='core_forms.questiongroups')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=None, max_length=255, null=True)),
                ('name', models.TextField()),
                ('order', models.BigIntegerField(default=None, null=True)),
                ('translations', models.JSONField(default=None, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_options', to='core_forms.questions')),
            ],
            options={
                'db_table': 'options',
            },
        ),
    ]
