# Generated by Django 4.2.1 on 2024-06-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_forms', '0003_alter_questions_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='label',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='options',
            name='value',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='questiongroups',
            name='label',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='display_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questions',
            name='label',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='pre',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='short_label',
            field=models.TextField(default=None, null=True),
        ),
    ]
