# Generated by Django 4.2.1 on 2024-06-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_forms', '0003_alter_questions_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='options',
            old_name='name',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='options',
            old_name='code',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='questiongroups',
            old_name='name',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='name',
            new_name='label',
        ),
        migrations.AddField(
            model_name='questions',
            name='display_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questions',
            name='pre',
            field=models.JSONField(default=None, null=True),
        ),
    ]
