# Generated by Django 4.2.1 on 2024-06-18 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_forms', '0004_options_label_options_value_questiongroups_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='name',
        ),
    ]
