# Generated by Django 4.2.1 on 2024-12-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_forms', '0007_questions_columns_questions_tree_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='addonAfter',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='addonBefore',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
